zip2_texas:
    resource: "@Zip2TexasBundle/Controller/"
    type:     annotation
    prefix:   /

VoteControllers:
    resource: "@Zip2VoteVoteBundle/Controller/"
    type:     annotation
    prefix:   /