<?php

namespace Zip2Vote\VoteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PollingLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollingLocationRepository extends EntityRepository
{
}
